### ISSUE TITLE
missing package requirements

### ISSUE THREAD

**Issue by samleenz** [HannahHuckstep/Db_Compare#1]
the R package `rmarkdown` is required for this to run but not specified in `README.md` 😱 

also! i think it'd be easier if you only listed package requirements that are not part of the base R or python install. Giving a conda YAML specification for making the environment could be a good idea (I can suppy this once my test run is successful)

**Comment by samleenz** [comment]
also, you say `request` is a python library requirement, should this be `requests`? (and so should `requests.adapters` be subsumed by that?)

**Comment by bhuvad** [comment]
I found a similar issue with installation requirements. Both `requests` and `request` are listed as requirements; are these meant to be the same? Another python requirement that is listed but I could not find is `urllibs`. I assume this is referring to the `urllib` library.

**Comment by samleenz** [comment]
also it may help to be more clear about how to ensure the right Java is installed! (or it may just be me that is constantly confused by java). this is specified more specifically in the conda env I'm setup thoughh

**Comment by bhuvad** [comment]
I would recommend that you specify the R packages that are part of Bioconductor as these can't be installed by `install.packages()`. I got an error (obviously) when installing them without `BiocManager`. I like @samleenz's idea of providing users with a YAML installation file.

**Comment by samleenz** [comment]
I'll push a change to `README.md` that replaces the requirements with a conda code example and also include an `env.yaml` if you'd like @HannahHuckstep ?

**Comment by HannahHuckstep** [comment]
Yes that'd be amazing! Thanks Sam !

**Comment by HannahHuckstep** [comment]
Also you are both right. 
So rmarkdown is required 
in python, it should be requests, as well as urllib

**Comment by HannahHuckstep** [comment]
Thanks Sam for the update !!
